# Generated by Django 5.1.6 on 2025-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Mail', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
